### ISSUE TITLE
Build jar includes bukkit and other dependencies

### ISSUE THREAD

**Issue by KarelPeeters** [EndlessCodeGroup/BukkitGradle#10]
The jar build by this plugin includes the whole `org.bukkit` package, even though that isn't necessary. I think it also includes Bukkits's dependencies.

In a normal gradle project I'd use `compileOnly` for bukkit, can you do something similar with this plugin?

**Comment by osipxd** [comment]
So strange, because I haven't this problem.

1. What version of BukkitGradle you use?
2. Have you read release notes for 0.7.0?

**Comment by KarelPeeters** [comment]
I was still on version `0.6.7` as suggested in `README.md`, I should have checked whether there was a newer version available, my bad. Everything works as expected after updating to `0.7.0`.

I suggest updating the README with the newest version to avoid future mistakes like this.

**Comment by osipxd** [comment]
Yes, I forgot to update README, I'll fix it soon.
