### ISSUE TITLE
PluginMeta default values

### ISSUE THREAD

**Issue by sionzee** [EndlessCodeGroup/BukkitGradle#12]
Hello, it's me again. I notice that, you're implemented default values for MetaItems in PluginMeta.groovy, but you are set these items as required. When you compile project without bukkit plugin meta, it will not compile and don't throw any error. Wouldn't be better to set required to false?

**Comment by osipxd** [comment]
Thanks for report, I'll check it

**Comment by osipxd** [comment]
Can't reproduce problem
