### ISSUE TITLE
Generated plugin yml does not contains quotes

### ISSUE THREAD

**Issue by sionzee** [EndlessCodeGroup/BukkitGradle#13]
Hello, when you are converting the groovy format to yml, can you surround the converted values? 
There is a problem when there are not quotes. It will throw a following error:

Ambiguous plugin name 'CommandsAPITest' for files 'plugins/CommandsAPITest-1.0-SNAPSHOT.jar' in 'plugins'

This is generated plugin.yml
```
name: CommandsAPITest
description: Yeah amazing plugin
main: cz.sionzee.commandsapi.test.CommandsAPITest
version: 1.0-SNAPSHOT
website: http://www.sionzee.cz
authors: [sionzee]
```

And the plugin meta
```groovy
    // Attributes for plugin.yml
    meta {
        name = "CommandsAPITest"
        description = "Yeah amazing plugin"
        main = "cz.sionzee.commandsapi.test.CommandsAPITest"
        version = "1.0-SNAPSHOT"
        url = "http://www.sionzee.cz" // Attribute website
        authors = ["sionzee"]
    }
```

**Comment by sionzee** [comment]
My temporary solution is add escaped quotes
```groovy
meta {
        name = "\"CommandsAPITest\""
        description = "\"Yeah amazing plugin\""
        main = "cz.sionzee.commandsapi.test.CommandsAPITest"
        version = "\"1.0-SNAPSHOT\""
        url = "\"http://www.sionzee.cz\"" // Attribute website
        authors = ["sionzee"]
    }
```
Then it will generate the correct format.

**Comment by osipxd** [comment]
So strange, I haven't such problem. Thanks for report, I'll check it

**Comment by osipxd** [comment]
I don't know why you need quotes around strings because YAML doesn't requires it and plugin works fine without it. And i haven't error `Ambiguous plugin name`.
But I've added for you functions `q` and `qq` in version 0.7.1.

Usage:
```groovy
q "single quoted value" // Returns `single quoted value`
qq "double quoted value" // Returns "double quoted value"
```
**Note:** In Groovy you can use functions with two ways: normal - `q("value")` and without braces - `q "value"`
