### ISSUE TITLE
Where to add a custom plugin.yml?

### ISSUE THREAD

**Issue by russjr08** [EndlessCodeGroup/BukkitGradle#23]
Hi!

Quick issue that I'm having, but I'm not sure where to place my custom plugin.yml file, for BukkitGradle to merge in custom attributes (I'm trying to set the api-version in my case).

I've tried putting it at the root of my project, as well as the src/main, and src/resources folder, but no luck. The documentation doesn't specify where to keep it at.

BukkitGradle is fantastic however, I appreciate the work you've put into it!

**Comment by osipxd** [comment]
Hi!

BukkitGradle doesn't affects it. plugin.yml should be in Gradle's resource folder  
By default: `src/main/resources/`.

**Comment by russjr08** [comment]
Wow, I can't believe it was that simple, thanks! 👍
