### ISSUE TITLE
Remove license violations

### ISSUE THREAD

**Issue by osipxd** [EndlessCodeGroup/BukkitGradle#3]
Downloading from Yive's Mirror violates license of Bukkit.
Need to use BuildTools for local building CraftBukkit and Spigot cores.
Relates to: https://github.com/minecraft-dev/MinecraftDev/issues/208

**Comment by osipxd** [comment]
I plan to add new extension `buildtools` to `bukkit`. Example:
```groovy
bukkit {
    buildtools {
        dir = "path/to/buildtools"
        bash = "path/to/git/bash" // For Windows
    }

    // Alternate initialization (if path to bash not needed)
    buildtools = "path/to/buildtools"
}
```

And add task `:buildCore` to build core selected in `api` option #4

**Comment by osipxd** [comment]
@DemonWav, it is possible to dinamically get latest build of Paperclip for needed version of minecraft?
At this moment I can only hardcode it.

**Comment by DenWav** [comment]
The links to the latest builds of PaperMC are [here](https://ci.destroystokyo.com/job/PaperSpigot/). Paper does not support old builds, so with the exception of extreme security issues, these builds are never going to change.

[1.10.2](https://ci.destroystokyo.com/job/PaperSpigot/916/)
[1.9.4](https://ci.destroystokyo.com/job/PaperSpigot/773/)
[1.8.8](https://ci.destroystokyo.com/job/PaperSpigot/443)

And 1.11.2 is latest.

As far as an automatic system for mapping MC versions to latest download links, that doesn't exist. An easy way to get around that would be to host a static JSON file (you could use gist to host it, and access it raw) with the MC versions and links supplied, and you could update that file when new versions come out.

**Comment by DenWav** [comment]
Also, running BuildTools from Gradle would be quite a slow process, and even worse if they have already got a build server jar and would just rather use it instead (if they are plugin developers, you can bet on it). I'm not sure if that's what you really want to do.

**Comment by osipxd** [comment]
BuildTools copies buid cores to local maven repository and it's possible to use it in all projects without rebuilding everytime. Gradle task `:buildCore` will be skipped if needed version of core already exists in local repo
