### ISSUE TITLE
Smarter plugin.yml

### ISSUE THREAD

**Issue by ryantheleach** [EndlessCodeGroup/BukkitGradle#30]
At the moment your build script will eat any existing plugin.yml changes, even if the variables havn't been defined correctly in build.gradle

It would be useful if the plugin did not modify plugin.yml attributes that had not been defined.

**Comment by ryantheleach** [comment]
It also won't let you specify api-version

**Comment by osipxd** [comment]
Thank you for the suggestion.

> At the moment your build script will eat any existing plugin.yml changes, even if the variables havn't been defined correctly in build.gradle  

It's not entirely true. Plugin removes only supported variables (authors, main, title, description, etc.) from plugin.yml. But should not affect any unsupported variables such as api-version, depends, permissions, etc.
I'll reconsider approach to generating plugin.yml to make in less breaking.

**Comment by ryantheleach** [comment]
Ah I'll give it another go, maybe I did something wrong.

**Comment by ryantheleach** [comment]
This plugin still eats plugin.yml files when they have been left undefined in build.gradle intentionally.

I can understand this behavior when they are defined, but before it is configured it should default to leaving plugin.yml alone.

**Comment by osipxd** [comment]
This behavior will be fixed with #41
