### ISSUE TITLE
Question: IntelliJ Debugging

### ISSUE THREAD

**Issue by Flaflo** [EndlessCodeGroup/BukkitGradle#35]
How is debugging the Plugin through IntelliJ supposed to work if the "debug" option is ignored?

Thanks in advance.

**Comment by osipxd** [comment]
With IDEA you should use task `buildIdeaRun`. You can run created with this task run configuration with debug if you want.
https://github.com/EndlessCodeGroup/BukkitGradle#running-dev-server

**Comment by Flaflo** [comment]
> 
> 
> With IDEA you should use task `buildIdeaRun`. You can run created with this task run configuration with debug if you want.
> https://github.com/EndlessCodeGroup/BukkitGradle#running-dev-server

Pressing on debug in IDEA with the generated Run Config does not work as far as I have tested. Hotswapping changes failes.

**Comment by osipxd** [comment]
Only Hotswap doesn't work? I'll check it.

**Comment by Flaflo** [comment]
Yes only Hotswapping is not working. I would appreciate it if you'll take a look at it!
