### ISSUE TITLE
Release a snapshot version of this plugin

### ISSUE THREAD

**Issue by stevefan1999-personal** [EndlessCodeGroup/BukkitGradle#40]
I uh, wanted to use this gradle plugin but it's currently stuck in 1.13, so I still have to manually copy my compiled plugins to my own Paper plugins folder, as I don't know how to compile a cloned gradle plugin from github and use it locally in the build system, would you like to either release the plugin as a snapshot/RC in your Maven central, or just tell me the instruction how to build the plugin from the cloned source?

**Comment by osipxd** [comment]
Hello!
Currently, the plugin is broken but I'll fix it ASAP. Now I have enough time to do it.
I think I'll release new version this week.

**Comment by osipxd** [comment]
Just for status. Still working on it.
