### ISSUE TITLE
Add overriding the dev server version to readme

### ISSUE THREAD

**Issue by ryantheleach** [EndlessCodeGroup/BukkitGradle#42]
I used this plugin as is, and it unexpectedly ran 1.15.1 as a dev server, without configuration.

I went to look to see how to configure the dev server version, but I could not see a method of doing so.

**Comment by osipxd** [comment]
Hello. At this moment version of dev server is equal to specified API version. I think I'll change this behavior in one of next versions.
https://github.com/EndlessCodeGroup/BukkitGradle#configuring-plugin
