### ISSUE TITLE
downloadServerCore task Download issue

### ISSUE THREAD

**Issue by kingdevnl** [EndlessCodeGroup/BukkitGradle#5]
Version: 0.6.9
Minecraft: 1.12.1-R0.1-SNAPSHOT-b1393
-So it trys to download https://yivesmirror.com/files/spigot/spigot-1.12.1-R0.1-SNAPSHOT.jar
But that link its 1 404

**Comment by osipxd** [comment]
Yes, it's known problem. Core downloading not work for versions 1.12+
Relates to #3

**Comment by KarelPeeters** [comment]
Is there a temporary workaround for this?

**Comment by osipxd** [comment]
@flaghacker, you can only download it manually and then: 
1. Copy run configuration "Run Server";
2. Remove Gradle task from run configuration dependencies
3. Use this task to run server

**Comment by KarelPeeters** [comment]
But doesnt't that also not copy the newest plugin jar?

**Comment by OsipXD** [comment]
Now I working on update
