### ISSUE TITLE
1.17/1.17.1 Support

### ISSUE THREAD

**Issue by russjr08** [EndlessCodeGroup/BukkitGradle#56]
Apologies if this issue needs to be created upstream and has nothing to do with BukkitGradle, however...

I was wondering if there is anything on my end that I need to do to build my plugin against the 1.17 API? I've tried setting my `apiVersion` to `1.17` which seems to fail to build with the following error:

```
Paper v1.17 not found.
Supported paper versions: [1.16.5, 1.16.4, 1.16.3, 1.16.2, 1.16.1, 1.15.2, 1.14.4, 1.13.2, 1.12.2, 1.11.2, 1.10.2, 1.9.4, 1.8.8].
```

Paper 1.17's API is [definitely available](https://papermc.io/using-the-api#kotlingradle), along with the [JavaDocs being available](https://papermc.io/javadocs/paper/1.17/) for 1.17 (and for 1.17.1 of course)

Unfortunately I'm not too familiar with how BukkitGradle's internals work, but if there is something I can try to work for to help include support for 1.17 - I'd love to give it a shot!

**Comment by osipxd** [comment]
Thank you for your report!

**Comment by osipxd** [comment]
Thank you for your report!
I've added 1.17 and 1.17.1 to [the list of supported versions](https://gist.github.com/osipxd/6119732e30059241c2192c4a8d2218d9). Can you check if it works now?

**Comment by russjr08** [comment]
Great! That seems to have done the trick.

Just as a heads up to anyone who is updating to 1.17/1.17.1 - remember that as of Minecraft 1.17 you need to have Java 16 installed, and you will need to update to Gradle 7 for Java 16 support as well or else you will get an error like this when building:

```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x1d2c1fa3) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x1d2c1fa3
```

If you're just using the gradle wrapper in your project, go into `gradle/wrapper/gradle-wrapper.properties` and set `distributionUrl` to a 7.x release, which right now the latest is `https\://services.gradle.org/distributions/gradle-7.1.1-bin.zip` - then try to build your project again.

**Comment by osipxd** [comment]
Another way to upgrade Gradle is running the following command (better to run it twice):
```sh
> ./gradlew wrapper --gradle-version=7.1.1
```
