### ISSUE TITLE
Does Bukkit Gradle support CraftBukkit?

### ISSUE THREAD

**Issue by Jpac14** [EndlessCodeGroup/BukkitGradle#57]
Hi,

I am trying to use the CraftBukkit API in my project so I can do some stuff with packets.

```groovy
plugins {
    id "ru.endlesscode.bukkitgradle" version "0.8.1"
}

dependencies {
    compileOnly bukkit()
    compile project(":common")
    testCompile bukkit()
}

jar {
   baseName = 'openstreetcraft-bukkit'
}
```

I do realise I am that I am using an older version BukkitGradle and Gradle but I sadly under my circumstances able to upgrade, if it is completely necessary, I could try and update but it would be very tedious. If it is not possible on this version then I will have to upgrade, would just like to know your thoughts.

Thanks

**Comment by osipxd** [comment]
Hello!
Try to replace `bukkit()` with `craftbukkit()`.
But it is important to know, that `craftbukkit()` was removed in BukkitGradle 0.9 and it is better to use `spigot()` instead.

**Comment by Jpac14** [comment]
Okay, I think this is solved now since I decide to use ProtocolLib instead. Thanks for your help @osipxd.
