### ISSUE TITLE
1.18 Release

### ISSUE THREAD

**Issue by russjr08** [EndlessCodeGroup/BukkitGradle#61]
Hello!

Paper 1.18 has been released for a bit now, the builds have progressed a bit. Currently, the latest 1.18 release is Build 58 at https://papermc.io/api/v2/projects/paper/versions/1.18/builds/58/downloads/paper-1.18-58.jar

Just requesting to have `paper-versions.json` updated 👍🏼 

Thanks!
Russ

**Comment by osipxd** [comment]
Thank you. I've updated [paper-versions.json](https://gist.github.com/osipxd/6119732e30059241c2192c4a8d2218d9) so you should be able to use 1.18
Check it, please

**Comment by russjr08** [comment]
Confirmed, thank you so much!
